name: AuctionHouse
version: 1.0.0
main: com.kingbrezz.auctionhouse.AuctionHousePlugin
api-version: '26.2'
folia-supported: true

author: KingBrezz

description: >
  Modern, lightweight Auction House plugin for Paper 26.2
  with GUI listings, sorting, searching, configurable prices,
  claims, pagination, taxes, listing fees and compact money formatting.

softdepend:
  - Vault

commands:
  ah:
    description: Open Auction House
    usage: /ah [sell|my|claims|search|reload]
    aliases:
      - auctionhouse

permissions:
  auctionhouse.use:
    description: Open Auction House
    default: true

  auctionhouse.sell:
    description: Create Auction House listings
    default: true

  auctionhouse.buy:
    description: Purchase Auction House listings
    default: true

  auctionhouse.admin:
    description: Reload Auction House
    default: op

  auctionhouse.limit.5:
    description: Allows 5 active auction listings
    default: true

  auctionhouse.limit.10:
    description: Allows 10 active auction listings
    default: false

  auctionhouse.limit.25:
    description: Allows 25 active auction listings
    default: false

  auctionhouse.limit.50:
    description: Allows 50 active auction listings
    default: false

  auctionhouse.limit.100:
    description: Allows 100 active auction listings
    default: false

  auctionhouse.limit.250:
    description: Allows 250 active auction listings
    default: false
